version="0.3.2"

[scripts]
run.cmd = [
    "cargo build --example module",
    "cargo run --example host -- target/debug/examples/module"
]
run.subcommands.wasm = [
    "cargo build --example module --target wasm32-wasi",
    "cargo run --example host -- target/wasm32-wasi/debug/examples/module.wasm true"
]
bench.cmd = [
    "cd benches/harness",
    "cargo run -- %num_runs"
]
bench.args = [ "num_runs" ]
