version="0.3.2"

[scripts]
run.cmd = [
    "cargo build --example module",
    "cargo run --example host -- target/debug/examples/module"
]
run.subcommands.wasm = [
    "cargo build --example module --target wasm32-wasi",
    "cargo run --example host -- target/wasm32-wasi/debug/examples/module.wasm true"
]
run.subcommands.async.cmd = [
    "cargo build --example async_module",
    "cargo run --example async_host -- target/debug/examples/async_module"
]
run.subcommands.async.subcommands.wasm = [
    "echo \"Sorry, but \\`tokio\\` doesn't support enough functionality to use IPFI's asynchronous API on Wasm just yet.\"",
    "exit 1"
]

bench.cmd = [
    "cd benches/harness",
    "cargo run -- %num_runs"
]
bench.args = [ "num_runs" ]
# Does 100k runs to make sure we get accurate results for publication
ci-bench = [
    "cd benches/harness",
    "cargo run -- 100000"
]

release = [
    # We allow specifying a custom version for pre-releases
    "standard-version --sign --commit-all %%",
    "git push --follow-tags origin main"
]
