[package]
name = "ipfi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = [ "derive" ] }
rmp-serde = "1"
rmp = "0.8"
thiserror = "1"
dashmap = "5.4.0"

[dev-dependencies]
once_cell = "1"
